Updated dependency check methods, removed unnecessary "exit 0"s

diff --git a/modules/EXAMPLE b/modules/EXAMPLE
--- a/modules/EXAMPLE
+++ b/modules/EXAMPLE
@@ -8,9 +8,9 @@
 # Check dependencies 
 if [[ "$1" == "--dep-check" ]]; then
 	depFail="0"
-	# Dependencies go in this array
 	# Dependencies already required by the controller script:
-	# read fgrep egrep echo cut sed ps awk
+	# bash awk date dd echo egrep fgrep mktemp printf ps pwd read sed source uname
+	# Dependencies go in this array
 	# Format is: deps=("foo" "bar")
 	deps=()
 	if [[ "${#deps[@]}" -ne "0" ]]; then
@@ -21,26 +21,48 @@ if [[ "$1" == "--dep-check" ]]; then
 			fi
 		done
 	fi
+
 	apiFail="0"
 	# API keys required should go in this array
 	# The value should be the variable name in api.conf
 	# Format is: apis=("imgurApi" "youTubeApiKey")
 	apis=()
 	if [[ "${#apis[@]}" -ne "0" ]]; then
-		for i in "${apis[@]}"; do
-			val="$(egrep "^${i}" "api.conf")"
-			val="${val#${i}=\"}"
-			val="${val%\"}"
-			if [[ -z "${val}" ]]; then
-				echo -e "Missing api key \"${red}${i}${reset}\"! Exiting."
-				apiFail="1"
-			fi
-		done
+		if [[ -e "api.conf" ]]; then
+			for i in "${apis[@]}"; do
+				val="$(egrep "^${i}" "api.conf")"
+				val="${val#${i}=\"}"
+				val="${val%\"}"
+				if [[ -z "${val}" ]]; then
+					echo -e "Missing api key \"${red}${i}${reset}\"! Exiting."
+					apiFail="1"
+				fi
+			done
+		else
+			path="$(pwd)"
+			path="${path##*/}"
+			path="./${path}/${0##*/}"
+			echo "Unable to locate \"api.conf\"!"
+			echo "(Are you running the dependency check from the main directory?)"
+			echo "(ex: ${path} --dep-check)"
+			exit 255
+		fi
 	fi
+
+	# If you need to check for MySQL support, check the variable ${sqlSupport}. If
+	# enabled, it will be 1. If disabled, it will be 0. You can uncomment the below
+	# statement if you need to require MySQL support.
+
+	# if [[ "${sqlSupport}" -eq "0" ]]; then
+	# 	echo "MySQL support required for this module, but not enabled!"
+	# 	depFail="1"
+	# fi
+
 	if [[ "${depFail}" -eq "0" ]] && [[ "${apiFail}" -eq "0" ]]; then
 		echo "ok"
 		exit 0
 	else
+		echo "Dependency check failed. See above errors."
 		exit 255
 	fi
 fi
