Modules can now check for an API key at dependency check; however, fine tuning will be required for the path to the API file to check

diff --git a/modules/EXAMPLE b/modules/EXAMPLE
--- a/modules/EXAMPLE
+++ b/modules/EXAMPLE
@@ -13,22 +13,35 @@ if [[ "$1" == "--dep-check" ]]; then
 	# read fgrep egrep echo cut sed ps awk
 	# Format is: deps=("foo" "bar")
 	deps=()
-	if [ "${#deps[@]}" -ne "0" ]; then
-		for i in ${deps[@]}; do
+	if [[ "${#deps[@]}" -ne "0" ]]; then
+		for i in "${deps[@]}"; do
 			if ! command -v ${i} > /dev/null 2>&1; then
 				echo -e "Missing dependency \"${red}${i}${reset}\"! Exiting."
 				depFail="1"
 			fi
 		done
-		if [ "${depFail}" -eq "1" ]; then
-			exit 1
-		else
-			echo "ok"
-			exit 0
-		fi
-	else
+	fi
+	apiFail="0"
+	# API keys required should go in this array
+	# The value should be the variable name in api.conf
+	# Format is: apis=("imgurApi" "youTubeApiKey")
+	apis=()
+	if [[ "${#apis[@]}" -ne "0" ]]; then
+		for i in "${apis[@]}"; do
+			val="$(egrep "^${i}" "api.conf")"
+			val="${val#${i}=\"}"
+			val="${val%\"}"
+			if [[ -z "${val}" ]]; then
+				echo -e "Missing api key \"${red}${i}${reset}\"! Exiting."
+				apiFail="1"
+			fi
+		done
+	fi
+	if [[ "${depFail}" -eq "0" ]] && [[ "${apiFail}" -eq "0" ]]; then
 		echo "ok"
 		exit 0
+	else
+		exit 255
 	fi
 fi
 
